module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'perf', 'refactor', 'docs', 'style', 'test', 'build', 'ci', 'chore', 'revert'],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'core',
        'config',
        'filesystem',
        'process',
        'remote',
        'opencode',
        'computer-use',
        'tunnel',
        'ui',
        'windows',
        'linux',
        'macos',
        'security',
        'server',
        'tools',
        'packaging',
        'ci',
        'deps',
        'docs',
        'governance',
        'release',
        'main',
      ],
    ],
    'scope-empty': [2, 'never'],
    'header-max-length': [2, 'always', 72],
  },
};
